#!/bin/bash

# Update package list and install nginx
apt-get update -y
apt-get install nginx -y

# Create custom HTML page containing "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.html

# Start nginx without using systemctl
service nginx start
